version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}-{{ arch }}
      - run:
          name: cache mods
          command: |
            go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}-{{ arch }}
          paths:
            - /go/pkg/mod
      - run:
          name: run tests
          command: |
            go test -v ./...
  proto-gen:
    macos:
      xcode: '11.3.0'
    steps:
      - checkout
      - run:
          name: install protobuf
          command: brew install protobuf
      - run:
          name: install grpc
          command: brew install grpc
      - run:
          name: install java grpc plugin
          command: |
            git clone https://github.com/grpc/grpc-java.git
            cd grpc-java/compiler
            ../gradlew java_pluginExecutable
            ../gradlew test

workflows:
  version: 2
  go-threads:
    jobs:
      # - test:
      #     filters:
      #       tags:
      #         only: /.*/
      - proto-gen:
          filters:
            tags:
              only: /.*/
